[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  path = "/collections"
  function = "og-meta"

[[edge_functions]]
  path = "/collections/*"
  function = "og-meta"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200